-- 코드를 입력하세요
WITH TARGET_BOOK_TBL AS (SELECT * FROM BOOK_SALES WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1),
TARGET_SALES_TBL AS (SELECT A.AUTHOR_ID AS AUTHOR_ID, CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
                    FROM TARGET_BOOK_TBL TB INNER JOIN BOOK B ON TB.BOOK_ID = B.BOOK_ID 
                                            INNER JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
                    GROUP BY A.AUTHOR_ID, CATEGORY)
SELECT TS.AUTHOR_ID, AUTHOR_NAME, CATEGORY, TOTAL_SALES
FROM TARGET_SALES_TBL TS LEFT JOIN AUTHOR A ON TS.AUTHOR_ID = A.AUTHOR_ID
ORDER BY AUTHOR_ID, CATEGORY DESC;