-- 코드를 입력하세요
SELECT ORDER_ID, PRODUCT_ID, DATE_FORMAT(OUT_DATE, '%Y-%m-%d') AS OUT_DATE,
    CASE
        WHEN OUT_DATE IS NULL
        THEN '출고미정'
        WHEN (YEAR(OUT_DATE) <= 2022 AND MONTH(OUT_DATE) < 5) OR
             (YEAR(OUT_DATE) = 2022 AND MONTH(OUT_DATE) = 5 AND DAY(OUT_DATE) = 1)
        THEN '출고완료'
        ELSE '출고대기'
    END 출고여부
FROM FOOD_ORDER
ORDER BY ORDER_ID;