-- 코드를 입력하세요
WITH TARGET_TBL AS (SELECT WRITER_ID
                    FROM USED_GOODS_BOARD
                    GROUP BY WRITER_ID
                    HAVING COUNT(*) >= 3)

SELECT UGU.USER_ID, UGU.NICKNAME, 
CONCAT(UGU.CITY, ' ', UGU.STREET_ADDRESS1, ' ', UGU.STREET_ADDRESS2) AS 전체주소, 
CONCAT(SUBSTRING(UGU.TLNO, 1, 3), '-', SUBSTRING(UGU.TLNO, 4, 4), '-', SUBSTRING(UGU.TLNO, 8, 4)) AS 전화번호
FROM TARGET_TBL TT INNER JOIN USED_GOODS_USER UGU ON TT.WRITER_ID = UGU.USER_ID
ORDER BY UGU.USER_ID DESC;