-- 코드를 입력하세요
SELECT YEAR(SALES_DATE), MONTH(SALES_DATE), COUNT(DISTINCT S.USER_ID) PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT S.USER_ID) / (SELECT COUNT(*) TOTAL_COUNT
                                       FROM USER_INFO
                                       WHERE YEAR(JOINED) = 2021), 1) PUCHASED_RATIO
FROM USER_INFO I INNER JOIN ONLINE_SALE S ON I.USER_ID = S.USER_ID
WHERE YEAR(JOINED) = 2021
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY 1, 2;;