-- 코드를 작성해주세요
WITH 
RECURSIVE RE AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT P.ID, GENERATION + 1
    FROM ECOLI_DATA P, RE C
    WHERE P.PARENT_ID = C.ID
),

NO_CHILD AS (
    SELECT R.ID, R.GENERATION
    FROM RE R
    LEFT JOIN ECOLI_DATA E ON R.ID = E.PARENT_ID
    WHERE E.ID IS NULL
)

-- 세대별 자식이 없는 개체의 수를 세고 세대를 오름차순으로 정렬
SELECT COUNT(*) AS COUNT, GENERATION
FROM NO_CHILD
GROUP BY GENERATION
ORDER BY GENERATION;