-- 코드를 작성해주세요
WITH QUARTER_TBL AS (SELECT ID, PARENT_ID, SIZE_OF_COLONY, GENOTYPE, 
                     IF(MONTH(DIFFERENTIATION_DATE) <= 3, '1Q', 
                        IF(MONTH(DIFFERENTIATION_DATE) <= 6, '2Q', 
                           IF(MONTH(DIFFERENTIATION_DATE) <= 9, '3Q', '4Q'))) AS QUARTER
                    FROM ECOLI_DATA)

SELECT QUARTER, COUNT(*) ECOLI_COUNT
FROM QUARTER_TBL
GROUP BY QUARTER
ORDER BY QUARTER;