WITH TRUCK_TBL AS (
    SELECT HISTORY_ID, DAILY_FEE, CAR_TYPE,
    CASE 
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90
        THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE=C.CAR_TYPE AND DURATION_TYPE LIKE '90%')
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30
        THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE=C.CAR_TYPE AND DURATION_TYPE LIKE '30%')
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7
        THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE=C.CAR_TYPE AND DURATION_TYPE LIKE '7%')
        ELSE 0
    END DISCOUNT_RATE,
    DATEDIFF(END_DATE, START_DATE) + 1 AS USED_DAY
    FROM CAR_RENTAL_COMPANY_CAR C INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH ON C.CAR_ID = RH.CAR_ID
)

SELECT HISTORY_ID, ROUND(DAILY_FEE * USED_DAY * (100 - DISCOUNT_RATE) / 100) AS FEE
FROM TRUCK_TBL
WHERE CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;