-- 코드를 입력하세요
WITH RECURSIVE CTE_COUNT AS (
SELECT 0 AS T
UNION ALL
SELECT T+1
FROM CTE_COUNT
WHERE T<23
)

SELECT T HOUR, COUNT(ANIMAL_ID) COUNT
FROM CTE_COUNT CC LEFT JOIN ANIMAL_OUTS AO ON CC.T = HOUR(AO.DATETIME)
GROUP BY 1
ORDER BY 1;