-- 코드를 입력하세요
WITH RECURSIVE TBL AS (
    SELECT 0 AS T
    UNION ALL
    SELECT T + 1
    FROM TBL
    WHERE T < 23
)

SELECT T HOUR, COUNT(ANIMAL_ID) COUNT
FROM TBL T LEFT JOIN ANIMAL_OUTS AO ON T.T = HOUR(AO.DATETIME)
GROUP BY T
ORDER BY HOUR;