-- 코드를 작성해주세요
WITH CHILD_TBL AS (SELECT IT.ITEM_ID
FROM ITEM_TREE IT INNER JOIN ITEM_INFO II ON IT.PARENT_ITEM_ID = II.ITEM_ID
WHERE RARITY = 'RARE')

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (SELECT * FROM CHILD_TBL)
ORDER BY 1 DESC;