-- ITEM_INFO에서 RARE인 애들만 추출
-- ITEM_TREE에서 ITEM_ID와 PARENT_ITEM_ID와 연결, 살아있는 ITEM_ID 추출
-- ITEM_INFO에서 ITEM_NAME을 JOIN

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (SELECT IT.ITEM_ID
                 FROM ITEM_INFO AS II LEFT JOIN ITEM_TREE IT ON II.ITEM_ID = IT.PARENT_ITEM_ID
                 WHERE II.RARITY = 'RARE')
ORDER BY ITEM_ID DESC;