-- 코드를 작성해주세요
WITH SKILL_TBL AS (SELECT * FROM SKILLCODES WHERE NAME IN ('Python', 'C#'))

SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS, SKILL_TBL
WHERE SKILL_CODE & CODE != 0
ORDER BY ID;