-- 코드를 작성해주세요
WITH MAX_SIZE_TBL AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, (MAX_SIZE - SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA ED INNER JOIN MAX_SIZE_TBL MST ON YEAR(DIFFERENTIATION_DATE) = MST.YEAR
ORDER BY YEAR, YEAR_DEV;