-- 코드를 작성해주세요
WITH AVG_SAL_TBL AS (
    SELECT DEPT_ID, ROUND(AVG(SAL)) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
)

SELECT HD.DEPT_ID, DEPT_NAME_EN, AVG_SAL
FROM HR_DEPARTMENT HD INNER join AVG_SAL_TBL AST on HD.DEPT_ID = AST.DEPT_ID
ORDER BY AVG_SAL DESC;

