-- 코드를 입력하세요
WITH TOP_VIEW AS (SELECT *
                 FROM USED_GOODS_BOARD
                 ORDER BY VIEWS DESC
                 LIMIT 1)

SELECT CONCAT('/home/grep/src/', TV.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) FILE_PATH
FROM TOP_VIEW TV INNER JOIN USED_GOODS_FILE UGF ON TV.BOARD_ID = UGF.BOARD_ID
ORDER BY FILE_ID DESC;