-- 코드를 입력하세요
WITH TOP_QUERY AS (SELECT BOARD_ID
                  FROM USED_GOODS_BOARD
                  ORDER BY VIEWS DESC
                  LIMIT 1)

SELECT CONCAT('/home/grep/src/', UGF.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) FILE_PATH
FROM USED_GOODS_FILE UGF INNER JOIN TOP_QUERY TQ ON UGF.BOARD_ID = TQ.BOARD_ID
ORDER BY FILE_ID DESC;